language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - master
    - "/^v?[0-9\\.]+$/"
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.8/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install v10.13.0
  - node --version
  - npm install
  - npm run extract
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
script:
  - composer test
before_deploy:
  - echo 'Making deploy packages...'
  - bash ./bin/cleanup.sh
  - zip -r bootstrapress.zip ./
